# Generated by Django 3.2.15 on 2023-09-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_alter_answer_poll'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='biography',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='name',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
