# Generated by Django 3.2.15 on 2023-10-04 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_alter_answer_poll'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='site',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
