# Generated by Django 3.2.15 on 2023-09-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20230927_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileform',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='site',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
