# Generated by Django 3.2.15 on 2023-09-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_add_description_field_to_site_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileform',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
