# Generated by Django 3.2.15 on 2023-09-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_site_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
