# Generated by Django 3.2.19 on 2023-09-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_site_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileform',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
