# Generated by Django 3.2.15 on 2023-10-04 15:19

from django.db import migrations, models

def migrate_form_fields_to_fields_data(apps, schema_editor):
    ProfileForm = apps.get_model('polls', 'ProfileForm')

    for profile_form in ProfileForm.objects.all():
        profile_form.fields_data = profile_form.form_fields
        profile_form.save()

class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_add_is_active_field_to_profile_form_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileform',
            name='fields_data',
            field=models.JSONField(null=True),
        ),
        migrations.RunPython(migrate_form_fields_to_fields_data),
    ]
