# Generated by Django 3.2.15 on 2023-09-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_profileform_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileform',
            name='fields_data',
            field=models.JSONField(null=True),
        ),
    ]
