# Generated by Django 3.2.15 on 2023-09-27 15:25

from django.db import migrations


def fill_bio_with_dynamic_fields(apps, _):
    Profile = apps.get_model('polls', 'Profile')
    profiles = Profile.objects.all()

    for profile in profiles:
        profile.bio = ''

        for key, value in profile.dynamic_fields.items():
            profile.bio += f'{key}: {value}'

    Profile.objects.bulk_update(profiles, ['bio'])


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_add_bio_to_profile'),
    ]

    operations = [
        migrations.RunPython(
            fill_bio_with_dynamic_fields,
            migrations.RunPython.noop,
            elidable=True,
        ),
    ]
