# Generated by Django 3.2.15 on 2023-09-27 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_profileform_fields_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileform',
            name='form_fields',
        ),
    ]
