# Generated by Django 3.2.19 on 2023-10-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_profileform_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileform',
            name='fields_data',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='profileform',
            name='form_fields',
            field=models.JSONField(null=True, editable=False),
        ),
    ]
