# Generated by Django 3.2.15 on 2023-10-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_profileform_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileform',
            name='fields_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
