# Generated by Django 3.2.15 on 2023-09-27 15:53

from django.db import migrations, models
from ..db.migration_operation import RemoveHiddenField


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_transfer_data_form_field_to_field_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileform',
            name='fields_data',
            field=models.JSONField(),
        ),
    ]