# Generated by Django 3.2.15 on 2023-09-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_hide_dynamic_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
