# Generated by Django 3.2.15 on 2023-09-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_transition_data_from_form_fields_to_new_fields_profile_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
