# Generated by Django 3.2.15 on 2023-09-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_hide_form_field_profile_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileform',
            name='fields_data',
            field=models.JSONField(null=True),
        ),
    ]
