# Generated by Django 3.2.15 on 2023-09-27 15:34

from django.db import migrations, models
from django.db.models import F


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_profileform_is_active'),
    ]

    def copy_field(apps, schema_editor):
        ProfileForm = apps.get_model('polls', 'ProfileForm')
        ProfileForm.objects.all().update(fields_data=F('form_fields'))

    operations = [
        migrations.AddField(
            model_name='profileform',
            name='fields_data',
            field=models.JSONField(null=True),
        ),

        migrations.RunPython(code=copy_field)
    ]
