# Generated by Django 3.2.15 on 2023-10-04 15:15

from django.db import migrations

def migrate_data(apps, schema_editor):
    Profile = apps.get_model('polls', 'Profile')
    profiles_to_update = []
    for profile in Profile.objects.all():
        profile.bio = profile.dynamic_fields
        profiles_to_update.append(profile)

    Profile.objects.bulk_update(profiles_to_update, ['bio'])



class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_profile_bio'),
    ]

    operations = [
        migrations.RunPython(migrate_data),
    ]
