# Generated by Django 3.2.15 on 2023-10-04 15:28

from django.db import migrations
from polls.migration_operation import HideField

class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_migrate_data'),
    ]

    operations = [
        HideField(
            model_name='Profile',
            name='dynamic_fields',
        )
    ]
